# The Docker image to run your workspace in. Defaults to gitpod/workspace-full
image: "ashdev/docker-spigot"
# Command to start on workspace startup (optional)
tasks:
  - command: "yarn install && yarn build"
# Ports to expose on workspace startup (optional)
ports:
  - port: 8000