language: java
sudo: false
install:
    - mkdir tmp
    - wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar -P /tmp/
script:
    - java -jar BuildTools.jar
    - mvn compile test
jdk:
  - oraclejdk8
#jdk
